backend:
  name: github
  repo: mmai/misc.rhumbs.fr
  branch: main
  base_url: https://misc.rhumbs.fr
output:
  omit_empty_optional_fields: true  
slug:
  encoding: ascii
  clean_accents: true  
media_folder: "static/uploads"
public_folder: "/uploads"
collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI
    folder: "content/blog" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    path: '{{slug}}/index'
    format: toml-frontmatter
    fields: # The fields for each document, usually in front matter
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - label: "Taxonomies"
        name: "taxonomies"
        widget: "object"
        fields:
          - label: "Tags"
            name: "tags"
            widget: "list"
            default: []
            required: false
      - { label: "Featured Image", name: "thumbnail", widget: "image", required: false }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "microblog" # Used in routes, e.g., /admin/collections/blog
    label: "Microblog" # Used in the UI
    folder: "content/microblog" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    path: '{{slug}}/index'
    format: toml-frontmatter
    fields: # The fields for each document, usually in front matter
      - name: date
        label: Publish Date
        widget: datetime
        default: '{{now}}'
        format: 'YYYY-MM-DDTHH:mm:ss'
        picker_utc: false
        required: false
        readonly: true
      - label: "Taxonomies"
        name: "taxonomies"
        widget: "object"
        fields:
          - label: "Tags"
            name: "tags"
            widget: "list"
            default: []
      - { label: "Body", name: "body", widget: "markdown" }
